# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña1', models.CharField(max_length=20)),
                ('tipodeusuario', models.CharField(max_length=20)),
                ('colegio', models.CharField(max_length=20)),
            ],
        ),
    ]
